### ISSUE TITLE
Line element models

### ISSUE THREAD

**Issue by JAMMIASHOK** [rhdodds/warp3d#10]
Dear sir,
Is it possible to incorporate beam. frame. truss elements in this code ? Does the source code extend well ? I mean can we write those elements - since material models are already robust - can we write elements that can call these materials at integration points ?

**Comment by rhdodds** [comment]
Hello,

Thanks for the inquiry and your interest in WARP3D.

The system was not designed from the beginning to support nodes with rotational degrees of freedom as required by beam, plate and shell elements. The focus of the code has always been 3D solid models. An enormous amount of work would be required to add support for elements with rotational dof.

We did add a 3D, 2-node truss element (bar2) with full geometric nonlinearity and material nonlinearity. A 3D version of a zero size "link" element is available. Sections 3.14, 3.15 of the User Manual. These often prove convenient to model certain boundary conditions (foundations, periodic conditions, etc.)

Bob Dodds

**Comment by JAMMIASHOK** [comment]
Thank you sir.
