### ISSUE TITLE
problem running warp3d.exe

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#11]
Hi, I read quickstart manual for windows(https://www.dropbox.com/s/dhs2yj78wka7bd3/QuickStart_Windows.pdf?dl=0), and when I ran warp3d\run_windows\warp3d.exe, this message appeared.

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, AVX and F16C instructions.

Is this problem of my processor? I use AMD Ryzen 9 5900X 12-Core Processor  by the way....

Thank you.

**Comment by rhdodds** [comment]
Hi Gyujang,

You likely know that Intel and AMD processors are not always 100% compatible.

I have built a new .exe for WARP3D that reduces the potential for conflicts with the instruction sets.

I do not have access to an AMD Windows machine so cannot confirm this fixes issue.

Please get the new executable here:

https://www.dropbox.com/s/1qsmrdcmzuji4vo/warp3d.exe?dl=0

Try this .exe and let me know the outcome of your test.

Best,

Bob

**Comment by vivelakorea** [comment]
I installed your file, but unfortunately same message occurs...

**Comment by rhdodds** [comment]
Hi Gyujang,

Very disappointed that the revised executable did not work on
your Ryzen processor.

Without access to such a machine, I am unable to test for the many
possible combinations of compiler options.

Best,

Bob
