### ISSUE TITLE
example 2 from chapter 1: no list of load steps found.

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#12]
Hi,
I am learning warp3d with manual, and I had a trouble running example 2 in manual_examples_chpt1 folder.
In example_2 folder, I ran

%warp% <warp3d.inp >out

in cmd(I set environment variable %warp% as written in quickstart guide), and got this error

 >>>>> error: no list of load steps found.
              scanning: all                                                                             
              keyword: all, may not be allowed here

        compute displacements for loadings upset step 1

Am I supposed to run another command line? I think there is load step at lines 30-32 in "wrap3d.inp"..

This was the entire output file..
![image](https://user-images.githubusercontent.com/40027828/145671723-7c465063-b83a-49ac-86e1-2645697613ae.png)
![image](https://user-images.githubusercontent.com/40027828/145671734-1a01305d-98f6-446b-8845-3a3f84756ede.png)
![image](https://user-images.githubusercontent.com/40027828/145671741-3f0dd118-a6d1-413f-8fea-bce0f6d270c9.png)
![image](https://user-images.githubusercontent.com/40027828/145671749-315aa616-ac15-4c00-9be5-8cef071dac31.png)

**Comment by rhdodds** [comment]
Hi G-


I had some input files containing deprecated options
on a few commands.

Please replace your example_2 directory with this one

https://www.dropbox.com/s/rgekrw08ps3jibc/example_2.zip?dl=0

I have updated the source on GitHub as well.

Prof. Dodds

**Comment by vivelakorea** [comment]
Thank

> Hi G-
> 
> I had some input files containing deprecated options on a few commands.
> 
> Please replace your example_2 directory with this one
> 
> https://www.dropbox.com/s/rgekrw08ps3jibc/example_2.zip?dl=0
> 
> I have updated the source on GitHub as well.
> 
> Prof. Dodds

Thanks, it works
