### ISSUE TITLE
formulation of mat_val1

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#14]
Hi,
So I am making the same model, which is tensile test of 1 element, by ABAQUS and WARP3D.
Since I have to compare PEEQ, I checked the c1_mat_val in paraview. Result was like this.
![image](https://user-images.githubusercontent.com/40027828/150942558-78c827b7-5179-488e-90ad-cf308f992e0e.png)
And for ABAQUS, PEEQ was like this.
![image](https://user-images.githubusercontent.com/40027828/150942639-795a1523-f9c0-48ad-803a-1ed5e1c10995.png)
So this was about sqrt(1.5) times bigger in WARP3D.
My question is that in manual chapter 3 - material mises, why does mat_val1 multiplies sqrt(1.5) in here?
![image](https://user-images.githubusercontent.com/40027828/150942932-28ba22da-b259-4432-9dc9-a5b196709f80.png)

Thanks.

**Comment by rhdodds** [comment]
Hello,

This is an old bug in the manual.

The equivalent plastic strain is being computed/output 
correctly.

I’m post an updated version of WARP3D & fixes in the manual
in a few days.

To check this issue, see input file below:

Uniaxial loading on a single element. Applied stress at end of
step 3 in 70 ski. Output value for c1 after step 3 is 0.099667
for \bar e^p.

Simple check:

   sig_xx at yield = 60 ski

   sig_xx after step 3  is 70.00000

   compute plastic modulus: H’ = E * E_T / (E - E_T)

   sig_xx change after yield is H’ * c1 = 10 ksi


Bob

!
!
!
!      Single element under monotonic tension. 
!
 structure patch
!
 material test
    properties bilinear e 30000 nu 0.3 tan_e 100  yld_pt 60.0
!     properties gurson e 30000 nu 0.3 tan_e 100  yld_pt 60.0
!
 number of nodes 8 elements 1
 coordinates
   1  1.0  1.0 0.0
   2  0.0  1.0 0.0
   3  1.0  0.0 0.0
   4  0.0  0.0 0.0
   5  1.0  1.0 1.0
   6  0.0  1.0 1.0
   7  1.0  0.0 1.0
   8  0.0  0.0 1.0
 elements
 1 type l3disop linear material test bbar,
    center_output short
 incidences 
   1    1 2 4 3 5 6 8 7
 blocking 
  1  1  1
 constraints
  2 4 u 0.0
  6 u 0.0 w 0.0
  8 u 0.0 v 0.0 w 0.0
 loading unit
   nodal loads
       1 3 5 7 force_x 0.25
 loading test
   nonlinear
    step   1   unit 59.9
    step   2   unit 1.1
    step   3   unit 9.0  $ total force = 70 (= 70 ksi stress)
!
  solution analysis parameters
   solution technique direct sparse
   maximum iterations 10
   minimum iterations 2   $ guarantee very small residuals
   convergence test norm res tol 0.001  maximum residual tol 0.001
   divergence check off
   time step  1.0e10
   trace solution on    $ reduce output volume
   adaptive solution on  $ never needed in this solution
   batch messages off
   extrapolate off        $ for load reversals
   material messages off
!
 compute displacements for loading test step 3
 output wide strains 1 stresses 1
 output flat text element stresses $ has same values as printed output above
 output flat text node stresses $ has same values as printed output above
!
 stop

**Comment by vivelakorea** [comment]
Thank you for your kind answer.
