### ISSUE TITLE
Tensile specimen with a central hole

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#15]
Hi.
Please forgive me for too many issues.

So I'm trying to make a tinsile test for a dog-bone specimen with centeral hole.
Result was like this.

![image](https://user-images.githubusercontent.com/40027828/152283885-6060b1cc-2bd4-4558-8deb-b26d945a632b.png)
Problem is that in real situation, most of strain is localized on center hole part of the neck. This is true in Abaqus as well. But the result shows that strain is only in top elements.

Could you tell me what is wrong in my file? I attatched my file - warp3d.inp, coordinates.inp, incidences.inp, get_output.inp below. (github issue doesn't support .inp file, so I uploaded it by text file)

Thanks.

[warp3d.txt](https://github.com/rhdodds/warp3d/files/7991951/warp3d.txt)
[coordinates.txt](https://github.com/rhdodds/warp3d/files/7991954/coordinates.txt)
[incidences.txt](https://github.com/rhdodds/warp3d/files/7991950/incidences.txt)
[get_output.txt](https://github.com/rhdodds/warp3d/files/7991944/get_output.txt)

**Comment by rhdodds** [comment]
Hello,

try this input file for a quasi-static solution.

For similar example with high-rate loading,
please study <warp3d>/verification/test78

Prof. Dodds

!
 structure CH
!
! TODO: get viscous exponent m_power, yield stress yld_pt, 
!        reference strain rate ref_eps, ...
 material aluminium
  properties mises e 70000 nu 0.3,
     yld_pt 385 tan_e 203 rho 0
!
 number of nodes 16887 elements 14688

 elements
  1-14688 type l3disop nonlinear material aluminium,
         bbar  order 2x2x2
 
 *input from file 'coordinates.txt'
 *input from file 'incidences.txt'

 blocking automatic

 constraints
  plane x=0 symmetry
  plane y=0 symmetry
  plane z=1.44000006 symmetry
  plane y=20. v 1
!
  output patran neutral "neutral.out"
  output model flat patran convention text file "model.text"

 loading pull
  nonlinear
    step 1-100 constraints 0.01

!
 nonlinear analysis parameters
   solution technique sparse direct
   time step 1.0e06
   maximum iterations 10 $ global Newton iterations
   minimum iterations 2
   extrapolate on
   convergence test norm res tol 0.01
   line search on
   divergence check on
   nonconvergent solutions stop
   adaptive on   $ global Newton iterations
   batch messages off
   wall time limit off
   material messages off
   bbar stabilization factor 0.0
   consistent q-matrix off
   trace solution on
   display tied mesh mpcs off
   user_routine off

!
 output commands use "get_output.txt" steps 1-1000
!
 compute displacements for loading pull,
   step 100
stop

**Comment by vivelakorea** [comment]
Thank you for your kind answer.
