### ISSUE TITLE
Simple Voce Hardening Models incorrect yield strength and UTS

### ISSUE THREAD

**Issue by wnoh3** [rhdodds/warp3d#20]
Hello,

I am running some tests on the crystal plasticity aspect of WARP3D. I ran a single element model in uniaxial tension conditions. I copied have the current material properties, though I have also attached the full inp file in this post. 

My understanding for CP in warp3d is that tau_y is the yield strength of the model, and tau_v is the hardening stress up to saturation. Therefore, tau_y and tau_v combine to be near 618.54 as the Ultimate Tensile Strength, but this does not seem to be the case when plotting the stress strain curve (see png in the zip). I have verified that the code to plot the stress strain curve should be free of bugs, so I am unsure what my error is. It could also very likely be lack of understanding of the subject, and if so, I would be very grateful if you could point me to specific literature to read. 

[singleelmforgit.zip](https://github.com/rhdodds/warp3d/files/13343927/singleelmforgit.zip)

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
crystal 1
     properties slip_type fcc elastic_type isotropic,
     hardening voce,
     e 59213.52 nu 0.3 harden_n 20,
     alter_mode on,
     theta_0 415 voce_m 1.0 tau_v 300 tau_y 318.54,
     gamma_bar 0.0005
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Thank you for your time!

**Comment by wnoh3** [comment]
Hello, 

I actually found my error! I was approaching the situation with an incorrect model and have fixed my specific situation.

**Comment by rhdodds** [comment]
Hello,

I also suggest that you examine CP examples in the directory: example_problems_cp (check the README)
Also the verification directory, sub-directories test74 and 82. These have additional examples illustrating the
CP material model.
